### ISSUE TITLE
bug: Module lacework_ecr failing due to variable

### ISSUE THREAD

**Issue by rym-dd** [lacework/terraform-aws-ecr#19]
**Describe the bug**
The module `lacework_ecr` is failing due to unexpected variable `non_os_package_support`.

**Steps to reproduce**
Add to your `main.tf` file : 
```
module "lacework_ecr" {
  source  = "lacework/ecr/aws"
  version = "~> 0.1"
}
```
Run: `terraform plan` => It will fail

Remove from the module this variable https://github.com/lacework/terraform-aws-ecr/blob/main/main.tf#L39 
Run: `terraform plan` => It will work.

**Expected behavior**
The module shouldn't fail due to this variable.

**Screenshots**
```tf
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/lacework_ecr/main.tf line 39, in resource "lacework_integration_ecr" "iam_role":
│   39:   non_os_package_support = var.non_os_package_support
│ 
│ An argument named "non_os_package_support" is not expected here.
╵
```

**Please complete the following information):**
 - Terraform Version: [v1.0.7]
 - Module Version: [lacework/ecr/aws 0.3.0] [lacework/iam-role/aws 0.2.2]

**Comment by cflond** [comment]
@rym-dd could you please confirm the version of the Lacework Provider please?

**Comment by rym-dd** [comment]
@cflond we are using 0.9 version. Trying with the lastest.

**Comment by rym-dd** [comment]
@cflond I confirm, it's working with 0.13 version. Thanks for your help and reactivity.

**Comment by afiune** [comment]
@rym-dd Thank you so much for opening this issue. @cflond Thank you for the prompt answer!

I'm glad you got all sorted out, though, I still consider this a bug since we are using an argument that from an spacific version of the Lacework provider so, we actually need to fix the issue by bumping the version constraint! Thank you again for poitint this out, we will get a fix soon. 🎉💯🙌🏽

**Comment by afiune** [comment]
Releasing a new version with the fix: https://github.com/lacework/terraform-aws-ecr/pull/21

![tenor-128030648](https://user-images.githubusercontent.com/5712253/146428096-e9f18196-31b9-463c-b1a3-49d27b1fcde7.gif)
