### ISSUE TITLE
bug:conflicting versions of lacework/lacework provider dependency

### ISSUE THREAD

**Issue by jaroslav-muller-jamf** [lacework/terraform-aws-ecr#59]
**Describe the bug**
I am getting a conflict in provider versions. Using module lacework_ecr that depends on lacework/lacework ~>1.1 and also depends on module lacework_ecr_iam_role ~> 0.4. However, this leads to using lacework_ecr_iam_role 0.4.5, which requires incompatible version of lacework/lacework ~> 2.0.

This is a snippet from `terraform providers`:
```
├── module.lacework_ecr
│   ├── provider[registry.terraform.io/hashicorp/aws] >= 3.0.0
│   ├── provider[registry.terraform.io/hashicorp/time] ~> 0.6
│   ├── provider[registry.terraform.io/lacework/lacework] ~> 1.1
│   └── module.lacework_ecr_iam_role
│       ├── provider[registry.terraform.io/hashicorp/random] >= 2.1.0
│       ├── provider[registry.terraform.io/lacework/lacework] ~> 2.0
│       └── provider[registry.terraform.io/hashicorp/aws] >= 3.0.0
```

As a result, running `terraform init -upgrade` leads to:
```
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider lacework/lacework: no available releases match the given constraints ~> 1.1, ~>
│ 2.0
╵
```

**Steps to reproduce**

**Expected behavior**
If lacework_ecr_iam_role requires major upgrade of a dependency, it should also increment its version to reflect the impact. In other words, lacework_ecr_iam_role should be 0.5.0. 
(Although I would argue, that if it is ment as semver, major increase in a dependency should imply major version increase here. So it would be 1.0.0. But it doesn't seem necessary to fix the bug.)

**Please complete the following information):**
 - Terraform Version: v1.5.7
 - Module Version (see the description)

**Comment by thekeys93** [comment]
Hello @jaroslav-muller-jamf.

We recently upgraded lacework provider to 2.0 and consequently all the modules. But in that process our major versions did not get updated for each of these modules (a mistake on our part).

Are you able to use the latest `lacework_ecr` as I believe that will remove the conflict

https://registry.terraform.io/modules/lacework/ecr/aws/0.9.3

**Comment by jaroslav-muller-jamf** [comment]
Yes, I have upgraded lacework_ecr and everything is ok. Just needed more reviews...

**Comment by p14n** [comment]
"If lacework_ecr_iam_role requires major upgrade of a dependency, it should also increment its version to reflect the impact. In other words, lacework_ecr_iam_role should be 0.5.0." - hard agree on this.  We use fixed versions to avoid this kind of issue and forcing a major upgrade on customers because of a minor internal upgrade is problematic.
